#pragma once
// by Asphodelus
// Auto Generated by MemHackProcessor [2026-03-05 13.07.05]



library AMHTrigger
	function MHTrigger_ClearEvent takes trigger trig returns boolean
		JapiPlaceHolder false
	endfunction
endlibrary
