#pragma once
// by Asphodelus
// Auto Generated by MemHackProcessor [2026-03-05 13.07.05]



library AMHAddonDebug
	function MHDebug_ExitWhenMapExisting takes string file returns nothing
		JapiPlaceHolderAddon
	endfunction
endlibrary
