#pragma once
// by Asphodelus
// Auto Generated by MemHackProcessor [2026-03-28 00.13.41]



#include "memory_hack_base.j"
#include "memory_hack_constant.j"

#if MEMHACK_INCLUDE_ALL
#include "api/ability.j"
#include "api/buff.j"
#include "api/constant.j"
#include "api/damage.j"
#include "api/debug.j"
#include "api/doodad.j"
#include "api/effect.j"
#include "api/event.j"
#include "api/frame.j"
#include "api/game.j"
#include "api/game_ui.j"
#include "api/game_ui_data.j"
#include "api/group.j"
#include "api/hashtable.j"
#include "api/hero.j"
#include "api/item.j"
#include "api/json.j"
#include "api/lua.j"
#include "api/math.j"
#include "api/message.j"
#include "api/missile.j"
#include "api/player.j"
#include "api/python.j"
#include "api/slk.j"
#include "api/string.j"
#include "api/sync.j"
#include "api/texttag.j"
#include "api/tool.j"
#include "api/trigger.j"
#include "api/unit.j"
#endif
