#pragma once
// by Asphodelus
// Auto Generated by MemHackProcessor [2026-03-14 00.14.40]



#include "memory_hack_addon_base.j"
#include "memory_hack_addon_constant.j"

#if MEMHACK_ADDON_INCLUDE_ALL
#include "api_addon/audio.j"
#include "api_addon/debug.j"
#include "api_addon/game.j"
#include "api_addon/http.j"
#include "api_addon/mpq.j"
#include "api_addon/tool.j"
#include "api_addon/websocket.j"
#endif
