---by Asphodelus
---Auto Generated by MemHackProcessor [2026-03-05 13.07.05]
---该文件可用作纯文档也可被require后使用
---@meta



---默认handle_level为0, handle直接以整数的形式传递
---@alias handle integer

---handle_level为1时, handle以视图(userdata)的方式传递
---不能与整数互相转换, 这与jass的行为一致, 但lua也不持有引用计数
---alias handle userdata

---handle_level为2时, handle以代理(userdata)的方式传递
---不能与整数转换, 同时lua会持有该handle的引用
---注意: 非常不推荐将handle_level设置为2
---会因为每个玩家的gc时机不同造成非常严重的异步!!!
---alias handle userdata

---你可以通过修改jass.runtime.handle_level来更改handle_level
---require'jass.runtime'.handle_level = 1
---建议只在开始时定好handle_level就不再修改了
local ai = require'jass.ai'


