---by Asphodelus
---Auto Generated by MemHackProcessor [2026-03-14 02.15.47]
---该文件可用作纯文档也可被require后使用
---@meta



---默认handle_level为0, handle直接以整数的形式传递
---@alias handle integer

---handle_level为1时, handle以视图(userdata)的方式传递
---不能与整数互相转换, 这与jass的行为一致, 但lua也不持有引用计数
---alias handle userdata

---handle_level为2时, handle以代理(userdata)的方式传递
---不能与整数转换, 同时lua会持有该handle的引用
---注意: 非常不推荐将handle_level设置为2
---会因为每个玩家的gc时机不同造成非常严重的异步!!!
---alias handle userdata

---你可以通过修改jass.runtime.handle_level来更改handle_level
---require'jass.runtime'.handle_level = 1
---建议只在开始时定好handle_level就不再修改了
local common = require'jass.common'





---@alias aidifficulty integer

---@type aidifficulty
---AI难度: 简单<br>
---来源: common.j
AI_DIFFICULTY_NEWBIE = common.AI_DIFFICULTY_NEWBIE
---@type aidifficulty
---AI难度: 普通<br>
---来源: common.j
AI_DIFFICULTY_NORMAL = common.AI_DIFFICULTY_NORMAL
---@type aidifficulty
---AI难度: 困难<br>
---来源: common.j
AI_DIFFICULTY_INSANE = common.AI_DIFFICULTY_INSANE



---@alias alliancetype integer

---@type alliancetype
---联盟类型: 结盟 (不侵犯)<br>
---来源: common.j
ALLIANCE_PASSIVE = common.ALLIANCE_PASSIVE
---@type alliancetype
---联盟类型: 救援请求<br>
---来源: common.j
ALLIANCE_HELP_REQUEST = common.ALLIANCE_HELP_REQUEST
---@type alliancetype
---联盟类型: 救援回应<br>
---来源: common.j
ALLIANCE_HELP_RESPONSE = common.ALLIANCE_HELP_RESPONSE
---@type alliancetype
---联盟类型: 共享经验值<br>
---来源: common.j
ALLIANCE_SHARED_XP = common.ALLIANCE_SHARED_XP
---@type alliancetype
---联盟类型: 盟友魔法锁定<br>
---来源: common.j
ALLIANCE_SHARED_SPELLS = common.ALLIANCE_SHARED_SPELLS
---@type alliancetype
---联盟类型: 共享视野<br>
---来源: common.j
ALLIANCE_SHARED_VISION = common.ALLIANCE_SHARED_VISION
---@type alliancetype
---联盟类型: 共享单位<br>
---来源: common.j
ALLIANCE_SHARED_CONTROL = common.ALLIANCE_SHARED_CONTROL
---@type alliancetype
---联盟类型: 完全共享单位控制<br>
---来源: common.j
ALLIANCE_SHARED_ADVANCED_CONTROL = common.ALLIANCE_SHARED_ADVANCED_CONTROL
---@type alliancetype
---联盟类型: 可营救<br>
---来源: common.j
ALLIANCE_RESCUABLE = common.ALLIANCE_RESCUABLE
---@type alliancetype
---联盟类型: 共享视野<br>
---来源: common.j
ALLIANCE_SHARED_VISION_FORCED = common.ALLIANCE_SHARED_VISION_FORCED



---@alias attacktype integer

---@type attacktype
---攻击类型: 法术<br>
---来源: common.j
ATTACK_TYPE_NORMAL = common.ATTACK_TYPE_NORMAL
---@type attacktype
---攻击类型: 普通<br>
---来源: common.j
ATTACK_TYPE_MELEE = common.ATTACK_TYPE_MELEE
---@type attacktype
---攻击类型: 穿刺<br>
---来源: common.j
ATTACK_TYPE_PIERCE = common.ATTACK_TYPE_PIERCE
---@type attacktype
---攻击类型: 攻城<br>
---来源: common.j
ATTACK_TYPE_SIEGE = common.ATTACK_TYPE_SIEGE
---@type attacktype
---攻击类型: 魔法<br>
---来源: common.j
ATTACK_TYPE_MAGIC = common.ATTACK_TYPE_MAGIC
---@type attacktype
---攻击类型: 混乱<br>
---来源: common.j
ATTACK_TYPE_CHAOS = common.ATTACK_TYPE_CHAOS
---@type attacktype
---攻击类型: 英雄<br>
---来源: common.j
ATTACK_TYPE_HERO = common.ATTACK_TYPE_HERO



---@alias blendmode integer

---@type blendmode
---混合方式: 无混合物<br>
---来源: common.j
BLEND_MODE_NONE = common.BLEND_MODE_NONE
---@type blendmode
---混合方式: 无视混合物<br>
---来源: common.j
BLEND_MODE_DONT_CARE = common.BLEND_MODE_DONT_CARE
---@type blendmode
---混合方式: 关键的alpha混合物<br>
---来源: common.j
BLEND_MODE_KEYALPHA = common.BLEND_MODE_KEYALPHA
---@type blendmode
---混合方式: 普通混合物<br>
---来源: common.j
BLEND_MODE_BLEND = common.BLEND_MODE_BLEND
---@type blendmode
---混合方式: 附加的混合物<br>
---来源: common.j
BLEND_MODE_ADDITIVE = common.BLEND_MODE_ADDITIVE
---@type blendmode
---混合方式: 调整的混合物<br>
---来源: common.j
BLEND_MODE_MODULATE = common.BLEND_MODE_MODULATE
---@type blendmode
---混合方式: 调整的2倍混合物<br>
---来源: common.j
BLEND_MODE_MODULATE_2X = common.BLEND_MODE_MODULATE_2X



---@alias camerafield integer

---@type camerafield
---镜头属性: 镜头距离<br>
---来源: common.j
CAMERA_FIELD_TARGET_DISTANCE = common.CAMERA_FIELD_TARGET_DISTANCE
---@type camerafield
---镜头属性: 远景裁剪<br>
---来源: common.j
CAMERA_FIELD_FARZ = common.CAMERA_FIELD_FARZ
---@type camerafield
---镜头属性: X 轴旋转角度<br>
---来源: common.j
CAMERA_FIELD_ANGLE_OF_ATTACK = common.CAMERA_FIELD_ANGLE_OF_ATTACK
---@type camerafield
---镜头属性: 镜头区域<br>
---来源: common.j
CAMERA_FIELD_FIELD_OF_VIEW = common.CAMERA_FIELD_FIELD_OF_VIEW
---@type camerafield
---镜头属性: Y 轴旋转角度<br>
---来源: common.j
CAMERA_FIELD_ROLL = common.CAMERA_FIELD_ROLL
---@type camerafield
---镜头属性: Z 轴旋转角度<br>
---来源: common.j
CAMERA_FIELD_ROTATION = common.CAMERA_FIELD_ROTATION
---@type camerafield
---镜头属性: Z 轴偏移<br>
---来源: common.j
CAMERA_FIELD_ZOFFSET = common.CAMERA_FIELD_ZOFFSET
---@type camerafield
---镜头属性: 近景裁剪<br>
---来源: common.j
CAMERA_FIELD_NEARZ = common.CAMERA_FIELD_NEARZ
---@type camerafield
---镜头属性: 局部纵摇(Z 轴)<br>
---来源: common.j
CAMERA_FIELD_LOCAL_PITCH = common.CAMERA_FIELD_LOCAL_PITCH
---@type camerafield
---镜头属性: 局部横摇(X 轴)<br>
---来源: common.j
CAMERA_FIELD_LOCAL_YAW = common.CAMERA_FIELD_LOCAL_YAW
---@type camerafield
---镜头属性: 局部滚摇(Y 轴)<br>
---来源: common.j
CAMERA_FIELD_LOCAL_ROLL = common.CAMERA_FIELD_LOCAL_ROLL



---@alias damagetype integer

---@type damagetype
---伤害类型: 未知<br>
---来源: common.j
DAMAGE_TYPE_UNKNOWN = common.DAMAGE_TYPE_UNKNOWN
---@type damagetype
---伤害类型: 普通<br>
---来源: common.j
DAMAGE_TYPE_NORMAL = common.DAMAGE_TYPE_NORMAL
---@type damagetype
---伤害类型: 强化<br>
---来源: common.j
DAMAGE_TYPE_ENHANCED = common.DAMAGE_TYPE_ENHANCED
---@type damagetype
---伤害类型: 火焰<br>
---来源: common.j
DAMAGE_TYPE_FIRE = common.DAMAGE_TYPE_FIRE
---@type damagetype
---伤害类型: 冰冻<br>
---来源: common.j
DAMAGE_TYPE_COLD = common.DAMAGE_TYPE_COLD
---@type damagetype
---伤害类型: 闪电<br>
---来源: common.j
DAMAGE_TYPE_LIGHTNING = common.DAMAGE_TYPE_LIGHTNING
---@type damagetype
---伤害类型: 毒药<br>
---来源: common.j
DAMAGE_TYPE_POISON = common.DAMAGE_TYPE_POISON
---@type damagetype
---伤害类型: 疾病<br>
---来源: common.j
DAMAGE_TYPE_DISEASE = common.DAMAGE_TYPE_DISEASE
---@type damagetype
---伤害类型: 神圣<br>
---来源: common.j
DAMAGE_TYPE_DIVINE = common.DAMAGE_TYPE_DIVINE
---@type damagetype
---伤害类型: 魔法<br>
---来源: common.j
DAMAGE_TYPE_MAGIC = common.DAMAGE_TYPE_MAGIC
---@type damagetype
---伤害类型: 音速<br>
---来源: common.j
DAMAGE_TYPE_SONIC = common.DAMAGE_TYPE_SONIC
---@type damagetype
---伤害类型: 酸性<br>
---来源: common.j
DAMAGE_TYPE_ACID = common.DAMAGE_TYPE_ACID
---@type damagetype
---伤害类型: 力量<br>
---来源: common.j
DAMAGE_TYPE_FORCE = common.DAMAGE_TYPE_FORCE
---@type damagetype
---伤害类型: 死亡<br>
---来源: common.j
DAMAGE_TYPE_DEATH = common.DAMAGE_TYPE_DEATH
---@type damagetype
---伤害类型: 精神<br>
---来源: common.j
DAMAGE_TYPE_MIND = common.DAMAGE_TYPE_MIND
---@type damagetype
---伤害类型: 植物<br>
---来源: common.j
DAMAGE_TYPE_PLANT = common.DAMAGE_TYPE_PLANT
---@type damagetype
---伤害类型: 防御<br>
---来源: common.j
DAMAGE_TYPE_DEFENSIVE = common.DAMAGE_TYPE_DEFENSIVE
---@type damagetype
---伤害类型: 破坏<br>
---来源: common.j
DAMAGE_TYPE_DEMOLITION = common.DAMAGE_TYPE_DEMOLITION
---@type damagetype
---伤害类型: 慢性毒药<br>
---来源: common.j
DAMAGE_TYPE_SLOW_POISON = common.DAMAGE_TYPE_SLOW_POISON
---@type damagetype
---伤害类型: 灵魂锁链<br>
---来源: common.j
DAMAGE_TYPE_SPIRIT_LINK = common.DAMAGE_TYPE_SPIRIT_LINK
---@type damagetype
---伤害类型: 暗影突袭<br>
---来源: common.j
DAMAGE_TYPE_SHADOW_STRIKE = common.DAMAGE_TYPE_SHADOW_STRIKE
---@type damagetype
---伤害类型: 通用<br>
---来源: common.j
DAMAGE_TYPE_UNIVERSAL = common.DAMAGE_TYPE_UNIVERSAL



---@alias dialogevent integer

---@type dialogevent
---对话框事件: 点击对话框按钮<br>
---来源: common.j
EVENT_DIALOG_BUTTON_CLICK = common.EVENT_DIALOG_BUTTON_CLICK
---@type dialogevent
---对话框事件: 点击对话框<br>
---来源: common.j
EVENT_DIALOG_CLICK = common.EVENT_DIALOG_CLICK



---@alias fogstate integer

---@type fogstate
---迷雾状态: 黑色阴影<br>
---来源: common.j
FOG_OF_WAR_MASKED = common.FOG_OF_WAR_MASKED
---@type fogstate
---迷雾状态: 战争迷雾<br>
---来源: common.j
FOG_OF_WAR_FOGGED = common.FOG_OF_WAR_FOGGED
---@type fogstate
---迷雾状态: 可见<br>
---来源: common.j
FOG_OF_WAR_VISIBLE = common.FOG_OF_WAR_VISIBLE



---@alias gamedifficulty integer

---@type gamedifficulty
---游戏难度: 简单<br>
---来源: common.j
MAP_DIFFICULTY_EASY = common.MAP_DIFFICULTY_EASY
---@type gamedifficulty
---游戏难度: 普通<br>
---来源: common.j
MAP_DIFFICULTY_NORMAL = common.MAP_DIFFICULTY_NORMAL
---@type gamedifficulty
---游戏难度: 困难<br>
---来源: common.j
MAP_DIFFICULTY_HARD = common.MAP_DIFFICULTY_HARD
---@type gamedifficulty
---游戏难度: 疯狂<br>
---来源: common.j
MAP_DIFFICULTY_INSANE = common.MAP_DIFFICULTY_INSANE



---@alias gameevent integer

---@type gameevent
---游戏事件: 游戏胜利<br>
---来源: common.j
EVENT_GAME_VICTORY = common.EVENT_GAME_VICTORY
---@type gameevent
---游戏事件: 游戏本关结束<br>
---来源: common.j
EVENT_GAME_END_LEVEL = common.EVENT_GAME_END_LEVEL
---@type gameevent
---游戏事件: 游戏变量变更<br>
---来源: common.j
EVENT_GAME_VARIABLE_LIMIT = common.EVENT_GAME_VARIABLE_LIMIT
---@type gameevent
---游戏事件: 游戏状态变更<br>
---来源: common.j
EVENT_GAME_STATE_LIMIT = common.EVENT_GAME_STATE_LIMIT
---@type gameevent
---游戏事件: 游戏超时<br>
---来源: common.j
EVENT_GAME_TIMER_EXPIRED = common.EVENT_GAME_TIMER_EXPIRED
---@type gameevent
---游戏事件: 进入区域<br>
---来源: common.j
EVENT_GAME_ENTER_REGION = common.EVENT_GAME_ENTER_REGION
---@type gameevent
---游戏事件: 离开区域<br>
---来源: common.j
EVENT_GAME_LEAVE_REGION = common.EVENT_GAME_LEAVE_REGION
---@type gameevent
---游戏事件: 鼠标点击可追踪物<br>
---来源: common.j
EVENT_GAME_TRACKABLE_HIT = common.EVENT_GAME_TRACKABLE_HIT
---@type gameevent
---游戏事件: 鼠标移动到可追踪物<br>
---来源: common.j
EVENT_GAME_TRACKABLE_TRACK = common.EVENT_GAME_TRACKABLE_TRACK
---@type gameevent
---游戏事件: 显示技能<br>
---来源: common.j
EVENT_GAME_SHOW_SKILL = common.EVENT_GAME_SHOW_SKILL
---@type gameevent
---游戏事件: 创建子菜单<br>
---来源: common.j
EVENT_GAME_BUILD_SUBMENU = common.EVENT_GAME_BUILD_SUBMENU
---@type gameevent
---游戏事件: 游戏加装完毕<br>
---来源: common.j
EVENT_GAME_LOADED = common.EVENT_GAME_LOADED
---@type gameevent
---游戏事件: 比赛即将完成<br>
---来源: common.j
EVENT_GAME_TOURNAMENT_FINISH_SOON = common.EVENT_GAME_TOURNAMENT_FINISH_SOON
---@type gameevent
---游戏事件: 比赛完成<br>
---来源: common.j
EVENT_GAME_TOURNAMENT_FINISH_NOW = common.EVENT_GAME_TOURNAMENT_FINISH_NOW
---@type gameevent
---游戏事件: 存档<br>
---来源: common.j
EVENT_GAME_SAVE = common.EVENT_GAME_SAVE



---@alias gamespeed integer

---@type gamespeed
---游戏速度: 最慢速<br>
---来源: common.j
MAP_SPEED_SLOWEST = common.MAP_SPEED_SLOWEST
---@type gamespeed
---游戏速度: 慢速<br>
---来源: common.j
MAP_SPEED_SLOW = common.MAP_SPEED_SLOW
---@type gamespeed
---游戏速度: 正常<br>
---来源: common.j
MAP_SPEED_NORMAL = common.MAP_SPEED_NORMAL
---@type gamespeed
---游戏速度: 快速<br>
---来源: common.j
MAP_SPEED_FAST = common.MAP_SPEED_FAST
---@type gamespeed
---游戏速度: 最快速<br>
---来源: common.j
MAP_SPEED_FASTEST = common.MAP_SPEED_FASTEST



---@alias itemtype integer

---@type itemtype
---物品分类: 永久<br>
---来源: common.j
ITEM_TYPE_PERMANENT = common.ITEM_TYPE_PERMANENT
---@type itemtype
---物品分类: 可充<br>
---来源: common.j
ITEM_TYPE_CHARGED = common.ITEM_TYPE_CHARGED
---@type itemtype
---物品分类: 力量提升<br>
---来源: common.j
ITEM_TYPE_POWERUP = common.ITEM_TYPE_POWERUP
---@type itemtype
---物品分类: 人造<br>
---来源: common.j
ITEM_TYPE_ARTIFACT = common.ITEM_TYPE_ARTIFACT
---@type itemtype
---物品分类: 可购买<br>
---来源: common.j
ITEM_TYPE_PURCHASABLE = common.ITEM_TYPE_PURCHASABLE
---@type itemtype
---物品分类: 战役<br>
---来源: common.j
ITEM_TYPE_CAMPAIGN = common.ITEM_TYPE_CAMPAIGN
---@type itemtype
---物品分类: 混杂 (假)<br>
---来源: common.j
ITEM_TYPE_MISCELLANEOUS = common.ITEM_TYPE_MISCELLANEOUS
---@type itemtype
---物品分类: 未知<br>
---来源: common.j
ITEM_TYPE_UNKNOWN = common.ITEM_TYPE_UNKNOWN
---@type itemtype
---物品分类: 任何<br>
---来源: common.j
ITEM_TYPE_ANY = common.ITEM_TYPE_ANY



---@alias limitop integer

---@type limitop
---变量事件: 小于<br>
---来源: common.j
LESS_THAN = common.LESS_THAN
---@type limitop
---变量事件: 小于 或 等于<br>
---来源: common.j
LESS_THAN_OR_EQUAL = common.LESS_THAN_OR_EQUAL
---@type limitop
---变量事件: 等于<br>
---来源: common.j
EQUAL = common.EQUAL
---@type limitop
---变量事件: 大于 或 等于<br>
---来源: common.j
GREATER_THAN_OR_EQUAL = common.GREATER_THAN_OR_EQUAL
---@type limitop
---变量事件: 大于<br>
---来源: common.j
GREATER_THAN = common.GREATER_THAN
---@type limitop
---变量事件: 不等于<br>
---来源: common.j
NOT_EQUAL = common.NOT_EQUAL



---@alias mapcontrol integer

---@type mapcontrol
---玩家控制者类型: 用户<br>
---默认值在情节-玩家设置编辑, 游戏初始化时会按房间的玩家使用情况(槽位是否有打开/无玩家, 玩家是电脑还是用户)再次设置<br>
---来源: common.j
MAP_CONTROL_USER = common.MAP_CONTROL_USER
---@type mapcontrol
---玩家控制者类型: 电脑<br>
---默认值在情节-玩家设置编辑, 游戏初始化时会按房间的玩家使用情况(槽位是否有打开/无玩家, 玩家是电脑还是用户)再次设置<br>
---来源: common.j
MAP_CONTROL_COMPUTER = common.MAP_CONTROL_COMPUTER
---@type mapcontrol
---玩家控制者类型: 中立可营救<br>
---默认值写死, 随版本12/24人自动变化, 即在1.29或以上版本运行低版本编辑器制作的地图时, 该值仍会自动适配<br>
---来源: common.j
MAP_CONTROL_RESCUABLE = common.MAP_CONTROL_RESCUABLE
---@type mapcontrol
---玩家控制者类型: 中立被动<br>
---默认值写死, 随版本12/24人自动变化, 即在1.29或以上版本运行低版本编辑器制作的地图时, 该值仍会自动适配<br>
---来源: common.j
MAP_CONTROL_NEUTRAL = common.MAP_CONTROL_NEUTRAL
---@type mapcontrol
---玩家控制者类型: 中立敌对<br>
---默认值写死, 随版本12/24人自动变化, 即在1.29或以上版本运行低版本编辑器制作的地图时, 该值仍会自动适配<br>
---来源: common.j
MAP_CONTROL_CREEP = common.MAP_CONTROL_CREEP
---@type mapcontrol
---玩家控制者类型: 没有玩家<br>
---默认值在情节-玩家设置编辑, 游戏初始化时会按房间的玩家使用情况(槽位是否有打开/无玩家, 玩家是电脑还是用户)再次设置<br>
---来源: common.j
MAP_CONTROL_NONE = common.MAP_CONTROL_NONE



---@alias mapflag integer

---@type mapflag
---地图参数: 隐藏地形<br>
---来源: common.j
MAP_FOG_HIDE_TERRAIN = common.MAP_FOG_HIDE_TERRAIN
---@type mapflag
---地图参数: 已探索地图/可见地形<br>
---来源: common.j
MAP_FOG_MAP_EXPLORED = common.MAP_FOG_MAP_EXPLORED
---@type mapflag
---地图参数: 始终可见<br>
---来源: common.j
MAP_FOG_ALWAYS_VISIBLE = common.MAP_FOG_ALWAYS_VISIBLE
---@type mapflag
---地图参数: 使用生命障碍<br>
---来源: common.j
MAP_USE_HANDICAPS = common.MAP_USE_HANDICAPS
---@type mapflag
---地图参数: 裁判/观战者<br>
---来源: common.j
MAP_OBSERVERS = common.MAP_OBSERVERS
---@type mapflag
---地图参数: 战败后成为观战者<br>
---来源: common.j
MAP_OBSERVERS_ON_DEATH = common.MAP_OBSERVERS_ON_DEATH
---@type mapflag
---地图参数: 固定玩家颜色<br>
---来源: common.j
MAP_FIXED_COLORS = common.MAP_FIXED_COLORS
---@type mapflag
---地图参数: 锁定交易资源 (禁止交易)<br>
---来源: common.j
MAP_LOCK_RESOURCE_TRADING = common.MAP_LOCK_RESOURCE_TRADING
---@type mapflag
---地图参数: 限制盟友资源交易<br>
---来源: common.j
MAP_RESOURCE_TRADING_ALLIES_ONLY = common.MAP_RESOURCE_TRADING_ALLIES_ONLY
---@type mapflag
---地图参数: 锁定联盟设置 (禁止更改)<br>
---来源: common.j
MAP_LOCK_ALLIANCE_CHANGES = common.MAP_LOCK_ALLIANCE_CHANGES
---@type mapflag
---地图参数: 隐藏联盟类型变更<br>
---来源: common.j
MAP_ALLIANCE_CHANGES_HIDDEN = common.MAP_ALLIANCE_CHANGES_HIDDEN
---@type mapflag
---地图参数: 作弊码<br>
---来源: common.j
MAP_CHEATS = common.MAP_CHEATS
---@type mapflag
---地图参数: 隐藏作弊码<br>
---来源: common.j
MAP_CHEATS_HIDDEN = common.MAP_CHEATS_HIDDEN
---@type mapflag
---地图参数: 锁定游戏速度<br>
---来源: common.j
MAP_LOCK_SPEED = common.MAP_LOCK_SPEED
---@type mapflag
---地图参数: 禁止随机游戏速度<br>
---来源: common.j
MAP_LOCK_RANDOM_SEED = common.MAP_LOCK_RANDOM_SEED
---@type mapflag
---地图参数: 共享高级控制<br>
---来源: common.j
MAP_SHARED_ADVANCED_CONTROL = common.MAP_SHARED_ADVANCED_CONTROL
---@type mapflag
---地图参数: 使用随机英雄<br>
---来源: common.j
MAP_RANDOM_HERO = common.MAP_RANDOM_HERO
---@type mapflag
---地图参数: 使用随机种族<br>
---来源: common.j
MAP_RANDOM_RACES = common.MAP_RANDOM_RACES
---@type mapflag
---地图参数: 地图转换 (加载新地图)<br>
---来源: common.j
MAP_RELOADED = common.MAP_RELOADED



---@alias pathingflag integer

---@type pathingflag
---放置要求: 地面可通行<br>
---来源: common.j
PATHING_FLAG_UNWALKABLE = common.PATHING_FLAG_UNWALKABLE
---@type pathingflag
---放置要求: 空中单位可通行<br>
---来源: common.j
PATHING_FLAG_UNFLYABLE = common.PATHING_FLAG_UNFLYABLE
---@type pathingflag
---放置要求: 可建造地面<br>
---来源: common.j
PATHING_FLAG_UNBUILDABLE = common.PATHING_FLAG_UNBUILDABLE
---@type pathingflag
---放置要求: 工人可采集<br>
---来源: common.j
PATHING_FLAG_UNPEONHARVEST = common.PATHING_FLAG_UNPEONHARVEST
---@type pathingflag
---放置要求: 不是荒芜地表<br>
---来源: common.j
PATHING_FLAG_BLIGHTED = common.PATHING_FLAG_BLIGHTED
---@type pathingflag
---放置要求: 海面可通行<br>
---来源: common.j
PATHING_FLAG_UNFLOATABLE = common.PATHING_FLAG_UNFLOATABLE
---@type pathingflag
---放置要求: 两栖单位可通行<br>
---来源: common.j
PATHING_FLAG_UNAMPHIBIOUS = common.PATHING_FLAG_UNAMPHIBIOUS
---@type pathingflag
---放置要求: 物品可通行<br>
---来源: common.j
PATHING_FLAG_UNITEMPLACABLE = common.PATHING_FLAG_UNITEMPLACABLE



---@alias pathingtype integer

---@type pathingtype
---路径类型: 任何<br>
---来源: common.j
PATHING_TYPE_ANY = common.PATHING_TYPE_ANY
---@type pathingtype
---路径类型: 可通行地面<br>
---来源: common.j
PATHING_TYPE_WALKABILITY = common.PATHING_TYPE_WALKABILITY
---@type pathingtype
---路径类型: 空中单位可通行<br>
---来源: common.j
PATHING_TYPE_FLYABILITY = common.PATHING_TYPE_FLYABILITY
---@type pathingtype
---路径类型: 可建造地面<br>
---来源: common.j
PATHING_TYPE_BUILDABILITY = common.PATHING_TYPE_BUILDABILITY
---@type pathingtype
---路径类型: 任何采集工人可通行<br>
---来源: common.j
PATHING_TYPE_PEONHARVESTPATHING = common.PATHING_TYPE_PEONHARVESTPATHING
---@type pathingtype
---路径类型: 荒芜地表<br>
---来源: common.j
PATHING_TYPE_BLIGHTPATHING = common.PATHING_TYPE_BLIGHTPATHING
---@type pathingtype
---路径类型: 可通行海面<br>
---来源: common.j
PATHING_TYPE_FLOATABILITY = common.PATHING_TYPE_FLOATABILITY
---@type pathingtype
---路径类型: 两栖单位可通行<br>
---来源: common.j
PATHING_TYPE_AMPHIBIOUSPATHING = common.PATHING_TYPE_AMPHIBIOUSPATHING



---@alias playercolor integer

---@type playercolor
---玩家颜色: 红色<br>
---代码: |cFFFF0000|r<br>
---三色值: 255, 3, 3<br>
---来源: common.j
PLAYER_COLOR_RED = common.PLAYER_COLOR_RED
---@type playercolor
---玩家颜色: 蓝色<br>
---代码: |cFF0064FF|r<br>
---三色值: 0, 66, 255<br>
---来源: common.j
PLAYER_COLOR_BLUE = common.PLAYER_COLOR_BLUE
---@type playercolor
---玩家颜色: 青色<br>
---代码: |cFF1BE7BA|r<br>
---三色值: 28, 230, 185<br>
---来源: common.j
PLAYER_COLOR_CYAN = common.PLAYER_COLOR_CYAN
---@type playercolor
---玩家颜色: 紫色<br>
---代码: |cFF550081|r<br>
---三色值: 84, 0, 129<br>
---来源: common.j
PLAYER_COLOR_PURPLE = common.PLAYER_COLOR_PURPLE
---@type playercolor
---玩家颜色: 黄色<br>
---代码: |cFFFFFC00|r<br>
---三色值: 255, 252, 0<br>
---来源: common.j
PLAYER_COLOR_YELLOW = common.PLAYER_COLOR_YELLOW
---@type playercolor
---玩家颜色: 橙色<br>
---代码: |cFFFF8A0D|r<br>
---三色值: 254, 138, 14<br>
---来源: common.j
PLAYER_COLOR_ORANGE = common.PLAYER_COLOR_ORANGE
---@type playercolor
---玩家颜色: 绿色<br>
---代码: |cFF21BF00|r<br>
---三色值: 32, 192, 0<br>
---来源: common.j
PLAYER_COLOR_GREEN = common.PLAYER_COLOR_GREEN
---@type playercolor
---玩家颜色: 粉色<br>
---代码: |cFFE45CAF|r<br>
---三色值: 229, 91, 176<br>
---来源: common.j
PLAYER_COLOR_PINK = common.PLAYER_COLOR_PINK
---@type playercolor
---玩家颜色: 深灰色<br>
---代码: |cFF949696|r<br>
---三色值: 149, 150, 151<br>
---来源: common.j
PLAYER_COLOR_LIGHT_GRAY = common.PLAYER_COLOR_LIGHT_GRAY
---@type playercolor
---玩家颜色: 深蓝色<br>
---代码: |cFF7EBFF1|r<br>
---三色值: 126, 191, 241<br>
---来源: common.j
PLAYER_COLOR_LIGHT_BLUE = common.PLAYER_COLOR_LIGHT_BLUE
---@type playercolor
---玩家颜色: 浅绿色<br>
---代码: |cFF106247|r<br>
---三色值: 16, 98, 70<br>
---来源: common.j
PLAYER_COLOR_AQUA = common.PLAYER_COLOR_AQUA
---@type playercolor
---玩家颜色: 棕色<br>
---代码: |cFF4F2B05|r<br>
---三色值: 78, 42, 3<br>
---来源: common.j
PLAYER_COLOR_BROWN = common.PLAYER_COLOR_BROWN



---@alias playerevent integer

---@type playerevent
---玩家事件: 玩家状态变更<br>
---来源: common.j
EVENT_PLAYER_STATE_LIMIT = common.EVENT_PLAYER_STATE_LIMIT
---@type playerevent
---玩家事件: 玩家联盟类型变更<br>
---来源: common.j
EVENT_PLAYER_ALLIANCE_CHANGED = common.EVENT_PLAYER_ALLIANCE_CHANGED
---@type playerevent
---玩家事件: 玩家失败<br>
---来源: common.j
EVENT_PLAYER_DEFEAT = common.EVENT_PLAYER_DEFEAT
---@type playerevent
---玩家事件: 玩家胜利<br>
---来源: common.j
EVENT_PLAYER_VICTORY = common.EVENT_PLAYER_VICTORY
---@type playerevent
---玩家事件: 玩家离开游戏<br>
---来源: common.j
EVENT_PLAYER_LEAVE = common.EVENT_PLAYER_LEAVE
---@type playerevent
---玩家事件: 玩家聊天<br>
---来源: common.j
EVENT_PLAYER_CHAT = common.EVENT_PLAYER_CHAT
---@type playerevent
---玩家事件: 玩家按下 ESC键<br>
---来源: common.j
EVENT_PLAYER_END_CINEMATIC = common.EVENT_PLAYER_END_CINEMATIC
---@type playerevent
---玩家事件: 按下 左方向键<br>
---来源: common.j
EVENT_PLAYER_ARROW_LEFT_DOWN = common.EVENT_PLAYER_ARROW_LEFT_DOWN
---@type playerevent
---玩家事件: 松开 左方向键<br>
---来源: common.j
EVENT_PLAYER_ARROW_LEFT_UP = common.EVENT_PLAYER_ARROW_LEFT_UP
---@type playerevent
---玩家事件: 按下 右方向键<br>
---来源: common.j
EVENT_PLAYER_ARROW_RIGHT_DOWN = common.EVENT_PLAYER_ARROW_RIGHT_DOWN
---@type playerevent
---玩家事件: 松开 右方向键<br>
---来源: common.j
EVENT_PLAYER_ARROW_RIGHT_UP = common.EVENT_PLAYER_ARROW_RIGHT_UP
---@type playerevent
---玩家事件: 按下 上方向键<br>
---来源: common.j
EVENT_PLAYER_ARROW_DOWN_DOWN = common.EVENT_PLAYER_ARROW_DOWN_DOWN
---@type playerevent
---玩家事件: 松开 上方向键<br>
---来源: common.j
EVENT_PLAYER_ARROW_DOWN_UP = common.EVENT_PLAYER_ARROW_DOWN_UP
---@type playerevent
---玩家事件: 按下 下方向键<br>
---来源: common.j
EVENT_PLAYER_ARROW_UP_DOWN = common.EVENT_PLAYER_ARROW_UP_DOWN
---@type playerevent
---玩家事件: 松开 下方向键<br>
---来源: common.j
EVENT_PLAYER_ARROW_UP_UP = common.EVENT_PLAYER_ARROW_UP_UP



---@alias playergameresult integer

---@type playergameresult
---玩家游戏结果: 胜利<br>
---来源: common.j
PLAYER_GAME_RESULT_VICTORY = common.PLAYER_GAME_RESULT_VICTORY
---@type playergameresult
---玩家游戏结果: 失败<br>
---来源: common.j
PLAYER_GAME_RESULT_DEFEAT = common.PLAYER_GAME_RESULT_DEFEAT
---@type playergameresult
---玩家游戏结果: 平局<br>
---来源: common.j
PLAYER_GAME_RESULT_TIE = common.PLAYER_GAME_RESULT_TIE
---@type playergameresult
---玩家游戏结果: 不确定<br>
---来源: common.j
PLAYER_GAME_RESULT_NEUTRAL = common.PLAYER_GAME_RESULT_NEUTRAL



---@alias playerscore integer

---@type playerscore
---玩家得分: 训练单位数量<br>
---来源: common.j
PLAYER_SCORE_UNITS_TRAINED = common.PLAYER_SCORE_UNITS_TRAINED
---@type playerscore
---玩家得分: 消灭单位数量<br>
---来源: common.j
PLAYER_SCORE_UNITS_KILLED = common.PLAYER_SCORE_UNITS_KILLED
---@type playerscore
---玩家得分: 已建造建筑数量<br>
---来源: common.j
PLAYER_SCORE_STRUCT_BUILT = common.PLAYER_SCORE_STRUCT_BUILT
---@type playerscore
---玩家得分: 被毁建筑数量<br>
---来源: common.j
PLAYER_SCORE_STRUCT_RAZED = common.PLAYER_SCORE_STRUCT_RAZED
---@type playerscore
---玩家得分: 科技百分比<br>
---来源: common.j
PLAYER_SCORE_TECH_PERCENT = common.PLAYER_SCORE_TECH_PERCENT
---@type playerscore
---玩家得分: 最大可用人口数量<br>
---来源: common.j
PLAYER_SCORE_FOOD_MAXPROD = common.PLAYER_SCORE_FOOD_MAXPROD
---@type playerscore
---玩家得分: 最大使用人口数量<br>
---来源: common.j
PLAYER_SCORE_FOOD_MAXUSED = common.PLAYER_SCORE_FOOD_MAXUSED
---@type playerscore
---玩家得分: 杀死英雄数量<br>
---来源: common.j
PLAYER_SCORE_HEROES_KILLED = common.PLAYER_SCORE_HEROES_KILLED
---@type playerscore
---玩家得分: 获得物品数量<br>
---来源: common.j
PLAYER_SCORE_ITEMS_GAINED = common.PLAYER_SCORE_ITEMS_GAINED
---@type playerscore
---玩家得分: 购买雇佣兵数量<br>
---来源: common.j
PLAYER_SCORE_MERCS_HIRED = common.PLAYER_SCORE_MERCS_HIRED
---@type playerscore
---玩家得分: 采集到的黄金数量(全部)<br>
---来源: common.j
PLAYER_SCORE_GOLD_MINED_TOTAL = common.PLAYER_SCORE_GOLD_MINED_TOTAL
---@type playerscore
---玩家得分: 采集到的黄金数量(维修费生效期间采集的)<br>
---来源: common.j
PLAYER_SCORE_GOLD_MINED_UPKEEP = common.PLAYER_SCORE_GOLD_MINED_UPKEEP
---@type playerscore
---玩家得分: 由于维修费而损失的黄金数量<br>
---来源: common.j
PLAYER_SCORE_GOLD_LOST_UPKEEP = common.PLAYER_SCORE_GOLD_LOST_UPKEEP
---@type playerscore
---玩家得分: 由于纳税损失的黄金数量<br>
---来源: common.j
PLAYER_SCORE_GOLD_LOST_TAX = common.PLAYER_SCORE_GOLD_LOST_TAX
---@type playerscore
---玩家得分: 给予盟友的黄金数量<br>
---来源: common.j
PLAYER_SCORE_GOLD_GIVEN = common.PLAYER_SCORE_GOLD_GIVEN
---@type playerscore
---玩家得分: 从盟友那收到的黄金数量<br>
---来源: common.j
PLAYER_SCORE_GOLD_RECEIVED = common.PLAYER_SCORE_GOLD_RECEIVED
---@type playerscore
---玩家得分: 采集到的木材数量<br>
---来源: common.j
PLAYER_SCORE_LUMBER_TOTAL = common.PLAYER_SCORE_LUMBER_TOTAL
---@type playerscore
---玩家得分: 由于维修费而损失的木材数量<br>
---来源: common.j
PLAYER_SCORE_LUMBER_LOST_UPKEEP = common.PLAYER_SCORE_LUMBER_LOST_UPKEEP
---@type playerscore
---玩家得分: 由于纳税损失的木材数量<br>
---来源: common.j
PLAYER_SCORE_LUMBER_LOST_TAX = common.PLAYER_SCORE_LUMBER_LOST_TAX
---@type playerscore
---玩家得分: 给予盟友的木材数量<br>
---来源: common.j
PLAYER_SCORE_LUMBER_GIVEN = common.PLAYER_SCORE_LUMBER_GIVEN
---@type playerscore
---玩家得分: 从盟友那收到的木材数量<br>
---来源: common.j
PLAYER_SCORE_LUMBER_RECEIVED = common.PLAYER_SCORE_LUMBER_RECEIVED
---@type playerscore
---玩家得分: 总的单位得分<br>
---来源: common.j
PLAYER_SCORE_UNIT_TOTAL = common.PLAYER_SCORE_UNIT_TOTAL
---@type playerscore
---玩家得分: 总的英雄得分<br>
---来源: common.j
PLAYER_SCORE_HERO_TOTAL = common.PLAYER_SCORE_HERO_TOTAL
---@type playerscore
---玩家得分: 总的资源得分<br>
---来源: common.j
PLAYER_SCORE_RESOURCE_TOTAL = common.PLAYER_SCORE_RESOURCE_TOTAL
---@type playerscore
---玩家得分: 总的整体得分<br>
---来源: common.j
PLAYER_SCORE_TOTAL = common.PLAYER_SCORE_TOTAL



---@alias playerslotstate integer

---@type playerslotstate
---玩家槽状态: 没有玩家使用<br>
---来源: common.j
PLAYER_SLOT_STATE_EMPTY = common.PLAYER_SLOT_STATE_EMPTY
---@type playerslotstate
---玩家槽状态: 玩家正在游戏<br>
---来源: common.j
PLAYER_SLOT_STATE_PLAYING = common.PLAYER_SLOT_STATE_PLAYING
---@type playerslotstate
---玩家槽状态: 玩家已离开游戏<br>
---来源: common.j
PLAYER_SLOT_STATE_LEFT = common.PLAYER_SLOT_STATE_LEFT



---@alias playerstate integer

---@type playerstate
---玩家状态: 现有黄金量<br>
---来源: common.j
PLAYER_STATE_RESOURCE_GOLD = common.PLAYER_STATE_RESOURCE_GOLD
---@type playerstate
---玩家状态: 现有木材量<br>
---来源: common.j
PLAYER_STATE_RESOURCE_LUMBER = common.PLAYER_STATE_RESOURCE_LUMBER
---@type playerstate
---玩家状态: 剩余可用英雄数<br>
---来源: common.j
PLAYER_STATE_RESOURCE_HERO_TOKENS = common.PLAYER_STATE_RESOURCE_HERO_TOKENS
---@type playerstate
---玩家状态: 可用人口数<br>
---默认为人口建筑提供的数量<br>
---来源: common.j
PLAYER_STATE_RESOURCE_FOOD_CAP = common.PLAYER_STATE_RESOURCE_FOOD_CAP
---@type playerstate
---玩家状态: 已使用人口数<br>
---来源: common.j
PLAYER_STATE_RESOURCE_FOOD_USED = common.PLAYER_STATE_RESOURCE_FOOD_USED
---@type playerstate
---玩家状态: 最大人口上限<br>
---平衡常数或触发限制的最大数量, 默认为100<br>
---来源: common.j
PLAYER_STATE_FOOD_CAP_CEILING = common.PLAYER_STATE_FOOD_CAP_CEILING
---@type playerstate
---玩家状态: 给予奖励<br>
---来源: common.j
PLAYER_STATE_GIVES_BOUNTY = common.PLAYER_STATE_GIVES_BOUNTY
---@type playerstate
---玩家状态: 联盟胜利<br>
---来源: common.j
PLAYER_STATE_ALLIED_VICTORY = common.PLAYER_STATE_ALLIED_VICTORY
---@type playerstate
---玩家状态: 放置<br>
---来源: common.j
PLAYER_STATE_PLACED = common.PLAYER_STATE_PLACED
---@type playerstate
---玩家状态: 战败后成为观战者<br>
---来源: common.j
PLAYER_STATE_OBSERVER_ON_DEATH = common.PLAYER_STATE_OBSERVER_ON_DEATH
---@type playerstate
---玩家状态: 裁判或观战者<br>
---来源: common.j
PLAYER_STATE_OBSERVER = common.PLAYER_STATE_OBSERVER
---@type playerstate
---玩家状态: 不可跟随<br>
---来源: common.j
PLAYER_STATE_UNFOLLOWABLE = common.PLAYER_STATE_UNFOLLOWABLE
---@type playerstate
---玩家状态: 黄金维修费率<br>
---来源: common.j
PLAYER_STATE_GOLD_UPKEEP_RATE = common.PLAYER_STATE_GOLD_UPKEEP_RATE
---@type playerstate
---玩家状态: 木材维修费率<br>
---来源: common.j
PLAYER_STATE_LUMBER_UPKEEP_RATE = common.PLAYER_STATE_LUMBER_UPKEEP_RATE
---@type playerstate
---玩家状态: 总金钱采集量<br>
---来源: common.j
PLAYER_STATE_GOLD_GATHERED = common.PLAYER_STATE_GOLD_GATHERED
---@type playerstate
---玩家状态: 总木材采集量<br>
---来源: common.j
PLAYER_STATE_LUMBER_GATHERED = common.PLAYER_STATE_LUMBER_GATHERED
---@type playerstate
---玩家状态: 中立敌对玩家单位睡眠<br>
---来源: common.j
PLAYER_STATE_NO_CREEP_SLEEP = common.PLAYER_STATE_NO_CREEP_SLEEP



---@alias playerunitevent integer

---@type playerunitevent
---玩家单位事件: 单位被攻击<br>
---来源: common.j
EVENT_PLAYER_UNIT_ATTACKED = common.EVENT_PLAYER_UNIT_ATTACKED
---@type playerunitevent
---玩家单位事件: 单位被营救<br>
---来源: common.j
EVENT_PLAYER_UNIT_RESCUED = common.EVENT_PLAYER_UNIT_RESCUED
---@type playerunitevent
---玩家单位事件: 单位死亡<br>
---来源: common.j
EVENT_PLAYER_UNIT_DEATH = common.EVENT_PLAYER_UNIT_DEATH
---@type playerunitevent
---玩家单位事件: 单位(尸体)开始腐烂<br>
---来源: common.j
EVENT_PLAYER_UNIT_DECAY = common.EVENT_PLAYER_UNIT_DECAY
---@type playerunitevent
---玩家单位事件: 单位可侦测<br>
---可被反隐看到<br>
---来源: common.j
EVENT_PLAYER_UNIT_DETECTED = common.EVENT_PLAYER_UNIT_DETECTED
---@type playerunitevent
---玩家单位事件: 单位被隐藏<br>
---来源: common.j
EVENT_PLAYER_UNIT_HIDDEN = common.EVENT_PLAYER_UNIT_HIDDEN
---@type playerunitevent
---玩家单位事件: 选择单位<br>
---来源: common.j
EVENT_PLAYER_UNIT_SELECTED = common.EVENT_PLAYER_UNIT_SELECTED
---@type playerunitevent
---玩家单位事件: 取消选择单位<br>
---来源: common.j
EVENT_PLAYER_UNIT_DESELECTED = common.EVENT_PLAYER_UNIT_DESELECTED
---@type playerunitevent
---玩家单位事件: 开始建造<br>
---来源: common.j
EVENT_PLAYER_UNIT_CONSTRUCT_START = common.EVENT_PLAYER_UNIT_CONSTRUCT_START
---@type playerunitevent
---玩家单位事件: 取消建造<br>
---来源: common.j
EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL = common.EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL
---@type playerunitevent
---玩家单位事件: 建造完成<br>
---来源: common.j
EVENT_PLAYER_UNIT_CONSTRUCT_FINISH = common.EVENT_PLAYER_UNIT_CONSTRUCT_FINISH
---@type playerunitevent
---玩家单位事件: 开始研究科技<br>
---来源: common.j
EVENT_PLAYER_UNIT_UPGRADE_START = common.EVENT_PLAYER_UNIT_UPGRADE_START
---@type playerunitevent
---玩家单位事件: 取消研究科技<br>
---来源: common.j
EVENT_PLAYER_UNIT_UPGRADE_CANCEL = common.EVENT_PLAYER_UNIT_UPGRADE_CANCEL
---@type playerunitevent
---玩家单位事件: 完成科技研究<br>
---来源: common.j
EVENT_PLAYER_UNIT_UPGRADE_FINISH = common.EVENT_PLAYER_UNIT_UPGRADE_FINISH
---@type playerunitevent
---玩家单位事件: 开始训练单位<br>
---来源: common.j
EVENT_PLAYER_UNIT_TRAIN_START = common.EVENT_PLAYER_UNIT_TRAIN_START
---@type playerunitevent
---玩家单位事件: 取消训练单位<br>
---来源: common.j
EVENT_PLAYER_UNIT_TRAIN_CANCEL = common.EVENT_PLAYER_UNIT_TRAIN_CANCEL
---@type playerunitevent
---玩家单位事件: 完成训练单位<br>
---来源: common.j
EVENT_PLAYER_UNIT_TRAIN_FINISH = common.EVENT_PLAYER_UNIT_TRAIN_FINISH
---@type playerunitevent
---玩家单位事件: 开始研究科技<br>
---来源: common.j
EVENT_PLAYER_UNIT_RESEARCH_START = common.EVENT_PLAYER_UNIT_RESEARCH_START
---@type playerunitevent
---玩家单位事件: 取消研究科技<br>
---来源: common.j
EVENT_PLAYER_UNIT_RESEARCH_CANCEL = common.EVENT_PLAYER_UNIT_RESEARCH_CANCEL
---@type playerunitevent
---玩家单位事件: 完成研究科技<br>
---来源: common.j
EVENT_PLAYER_UNIT_RESEARCH_FINISH = common.EVENT_PLAYER_UNIT_RESEARCH_FINISH
---@type playerunitevent
---玩家单位事件: 发布命令 (无目标)<br>
---来源: common.j
EVENT_PLAYER_UNIT_ISSUED_ORDER = common.EVENT_PLAYER_UNIT_ISSUED_ORDER
---@type playerunitevent
---玩家单位事件: 发布命令 (指定点)<br>
---来源: common.j
EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER = common.EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER
---@type playerunitevent
---玩家单位事件: 发布命令 (指定单位)<br>
---来源: common.j
EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER = common.EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER
---@type playerunitevent
---玩家单位事件: 发布命令 (指定单位)<br>
---来源: common.j
EVENT_PLAYER_UNIT_ISSUED_UNIT_ORDER = common.EVENT_PLAYER_UNIT_ISSUED_UNIT_ORDER
---@type playerunitevent
---玩家单位事件: 英雄升级<br>
---来源: common.j
EVENT_PLAYER_HERO_LEVEL = common.EVENT_PLAYER_HERO_LEVEL
---@type playerunitevent
---玩家单位事件: 英雄学习技能<br>
---来源: common.j
EVENT_PLAYER_HERO_SKILL = common.EVENT_PLAYER_HERO_SKILL
---@type playerunitevent
---玩家单位事件: 英雄可复活/阵亡<br>
---来源: common.j
EVENT_PLAYER_HERO_REVIVABLE = common.EVENT_PLAYER_HERO_REVIVABLE
---@type playerunitevent
---玩家单位事件: 英雄开始复活<br>
---来源: common.j
EVENT_PLAYER_HERO_REVIVE_START = common.EVENT_PLAYER_HERO_REVIVE_START
---@type playerunitevent
---玩家单位事件: 英雄取消复活<br>
---来源: common.j
EVENT_PLAYER_HERO_REVIVE_CANCEL = common.EVENT_PLAYER_HERO_REVIVE_CANCEL
---@type playerunitevent
---玩家单位事件: 英雄完成复活<br>
---来源: common.j
EVENT_PLAYER_HERO_REVIVE_FINISH = common.EVENT_PLAYER_HERO_REVIVE_FINISH
---@type playerunitevent
---玩家单位事件: 召唤单位<br>
---来源: common.j
EVENT_PLAYER_UNIT_SUMMON = common.EVENT_PLAYER_UNIT_SUMMON
---@type playerunitevent
---玩家单位事件: 物品掉落<br>
---来源: common.j
EVENT_PLAYER_UNIT_DROP_ITEM = common.EVENT_PLAYER_UNIT_DROP_ITEM
---@type playerunitevent
---玩家单位事件: 拾取物品<br>
---来源: common.j
EVENT_PLAYER_UNIT_PICKUP_ITEM = common.EVENT_PLAYER_UNIT_PICKUP_ITEM
---@type playerunitevent
---玩家单位事件: 使用物品<br>
---来源: common.j
EVENT_PLAYER_UNIT_USE_ITEM = common.EVENT_PLAYER_UNIT_USE_ITEM
---@type playerunitevent
---玩家单位事件: 单位被装载<br>
---被飞艇、船、被缠绕的金矿等装载<br>
---来源: common.j
EVENT_PLAYER_UNIT_LOADED = common.EVENT_PLAYER_UNIT_LOADED
---@type playerunitevent
---玩家单位事件: 单位被伤害<br>
---来源: common.j
EVENT_PLAYER_UNIT_DAMAGED = common.EVENT_PLAYER_UNIT_DAMAGED
---@type playerunitevent
---玩家单位事件: 单位造成伤害<br>
---来源: common.j
EVENT_PLAYER_UNIT_DAMAGING = common.EVENT_PLAYER_UNIT_DAMAGING
---@type playerunitevent
---玩家单位事件: 出售单位<br>
---来源: common.j
EVENT_PLAYER_UNIT_SELL = common.EVENT_PLAYER_UNIT_SELL
---@type playerunitevent
---玩家单位事件: 变更所属<br>
---来源: common.j
EVENT_PLAYER_UNIT_CHANGE_OWNER = common.EVENT_PLAYER_UNIT_CHANGE_OWNER
---@type playerunitevent
---玩家单位事件: 出售物品<br>
---来源: common.j
EVENT_PLAYER_UNIT_SELL_ITEM = common.EVENT_PLAYER_UNIT_SELL_ITEM
---@type playerunitevent
---玩家单位事件: 准备施放技能 (前摇开始)<br>
---来源: common.j
EVENT_PLAYER_UNIT_SPELL_CHANNEL = common.EVENT_PLAYER_UNIT_SPELL_CHANNEL
---@type playerunitevent
---玩家单位事件: 开始施放技能(前摇结束)<br>
---来源: common.j
EVENT_PLAYER_UNIT_SPELL_CAST = common.EVENT_PLAYER_UNIT_SPELL_CAST
---@type playerunitevent
---玩家单位事件: 发动技能效果(后摇开始)<br>
---来源: common.j
EVENT_PLAYER_UNIT_SPELL_EFFECT = common.EVENT_PLAYER_UNIT_SPELL_EFFECT
---@type playerunitevent
---玩家单位事件: 释放技能結束 (后摇结束)<br>
---来源: common.j
EVENT_PLAYER_UNIT_SPELL_FINISH = common.EVENT_PLAYER_UNIT_SPELL_FINISH
---@type playerunitevent
---玩家单位事件: 停止施放技能<br>
---来源: common.j
EVENT_PLAYER_UNIT_SPELL_ENDCAST = common.EVENT_PLAYER_UNIT_SPELL_ENDCAST
---@type playerunitevent
---玩家单位事件: 抵押(卖)物品<br>
---来源: common.j
EVENT_PLAYER_UNIT_PAWN_ITEM = common.EVENT_PLAYER_UNIT_PAWN_ITEM
---@type playerunitevent
---玩家单位事件: 堆叠物品<br>
---来源: common.j
EVENT_PLAYER_UNIT_STACK_ITEM = common.EVENT_PLAYER_UNIT_STACK_ITEM



---@alias race integer

---@type race
---种族: 人类<br>
---来源: common.j
RACE_HUMAN = common.RACE_HUMAN
---@type race
---种族: 兽人<br>
---来源: common.j
RACE_ORC = common.RACE_ORC
---@type race
---种族: 不死族<br>
---来源: common.j
RACE_UNDEAD = common.RACE_UNDEAD
---@type race
---种族: 暗夜精灵<br>
---来源: common.j
RACE_NIGHTELF = common.RACE_NIGHTELF
---@type race
---种族: 恶魔族<br>
---来源: common.j
RACE_DEMON = common.RACE_DEMON
---@type race
---种族: 其他<br>
---来源: common.j
RACE_OTHER = common.RACE_OTHER



---@alias racepreference integer

---@type racepreference
---预设玩家种族: 人类<br>
---来源: common.j
RACE_PREF_HUMAN = common.RACE_PREF_HUMAN
---@type racepreference
---预设玩家种族: 兽人<br>
---来源: common.j
RACE_PREF_ORC = common.RACE_PREF_ORC
---@type racepreference
---预设玩家种族: 暗夜精灵<br>
---来源: common.j
RACE_PREF_NIGHTELF = common.RACE_PREF_NIGHTELF
---@type racepreference
---预设玩家种族: 不死族<br>
---来源: common.j
RACE_PREF_UNDEAD = common.RACE_PREF_UNDEAD
---@type racepreference
---预设玩家种族: 恶魔<br>
---来源: common.j
RACE_PREF_DEMON = common.RACE_PREF_DEMON
---@type racepreference
---预设玩家种族: 随机<br>
---来源: common.j
RACE_PREF_RANDOM = common.RACE_PREF_RANDOM
---@type racepreference
---预设玩家种族: 用户可选择<br>
---来源: common.j
RACE_PREF_USER_SELECTABLE = common.RACE_PREF_USER_SELECTABLE



---@alias texmapflags integer

---@type texmapflags
---纹理贴图标志: 无<br>
---来源: common.j
TEXMAP_FLAG_NONE = common.TEXMAP_FLAG_NONE
---@type texmapflags
---纹理贴图标志: 重叠 (U)<br>
---来源: common.j
TEXMAP_FLAG_WRAP_U = common.TEXMAP_FLAG_WRAP_U
---@type texmapflags
---纹理贴图标志: 重叠 (V)<br>
---来源: common.j
TEXMAP_FLAG_WRAP_V = common.TEXMAP_FLAG_WRAP_V
---@type texmapflags
---纹理贴图标志: 重叠 (UV)<br>
---来源: common.j
TEXMAP_FLAG_WRAP_UV = common.TEXMAP_FLAG_WRAP_UV



---@alias unitevent integer

---@type unitevent
---单位事件: 单位受到伤害<br>
---来源: common.j
EVENT_UNIT_DAMAGED = common.EVENT_UNIT_DAMAGED
---@type unitevent
---单位事件: 单位死亡<br>
---来源: common.j
EVENT_UNIT_DEATH = common.EVENT_UNIT_DEATH
---@type unitevent
---单位事件: 单位(尸体)开始腐烂<br>
---来源: common.j
EVENT_UNIT_DECAY = common.EVENT_UNIT_DECAY
---@type unitevent
---单位事件: 单位可侦测<br>
---可被反隐看到<br>
---来源: common.j
EVENT_UNIT_DETECTED = common.EVENT_UNIT_DETECTED
---@type unitevent
---单位事件: 单位被隐藏<br>
---来源: common.j
EVENT_UNIT_HIDDEN = common.EVENT_UNIT_HIDDEN
---@type unitevent
---单位事件: 选择单位<br>
---来源: common.j
EVENT_UNIT_SELECTED = common.EVENT_UNIT_SELECTED
---@type unitevent
---单位事件: 取消选择单位<br>
---来源: common.j
EVENT_UNIT_DESELECTED = common.EVENT_UNIT_DESELECTED
---@type unitevent
---单位事件: 单位状态变更<br>
---来源: common.j
EVENT_UNIT_STATE_LIMIT = common.EVENT_UNIT_STATE_LIMIT
---@type unitevent
---单位事件: 单位获取到攻击目标<br>
---类似触发单位警戒攻击<br>
---来源: common.j
EVENT_UNIT_ACQUIRED_TARGET = common.EVENT_UNIT_ACQUIRED_TARGET
---@type unitevent
---单位事件: 目标在单位获取范围内<br>
---类似警戒范围<br>
---来源: common.j
EVENT_UNIT_TARGET_IN_RANGE = common.EVENT_UNIT_TARGET_IN_RANGE
---@type unitevent
---单位事件: 单位被攻击<br>
---来源: common.j
EVENT_UNIT_ATTACKED = common.EVENT_UNIT_ATTACKED
---@type unitevent
---单位事件: 单位被营救<br>
---来源: common.j
EVENT_UNIT_RESCUED = common.EVENT_UNIT_RESCUED
---@type unitevent
---单位事件: 取消建造<br>
---来源: common.j
EVENT_UNIT_CONSTRUCT_CANCEL = common.EVENT_UNIT_CONSTRUCT_CANCEL
---@type unitevent
---单位事件: 完成建造<br>
---来源: common.j
EVENT_UNIT_CONSTRUCT_FINISH = common.EVENT_UNIT_CONSTRUCT_FINISH
---@type unitevent
---单位事件: 开始研究科技<br>
---来源: common.j
EVENT_UNIT_UPGRADE_START = common.EVENT_UNIT_UPGRADE_START
---@type unitevent
---单位事件: 取消研究科技<br>
---来源: common.j
EVENT_UNIT_UPGRADE_CANCEL = common.EVENT_UNIT_UPGRADE_CANCEL
---@type unitevent
---单位事件: 完成研究科技<br>
---来源: common.j
EVENT_UNIT_UPGRADE_FINISH = common.EVENT_UNIT_UPGRADE_FINISH
---@type unitevent
---单位事件: 开始训练单位<br>
---来源: common.j
EVENT_UNIT_TRAIN_START = common.EVENT_UNIT_TRAIN_START
---@type unitevent
---单位事件: 取消训练单位<br>
---来源: common.j
EVENT_UNIT_TRAIN_CANCEL = common.EVENT_UNIT_TRAIN_CANCEL
---@type unitevent
---单位事件: 完成训练单位<br>
---来源: common.j
EVENT_UNIT_TRAIN_FINISH = common.EVENT_UNIT_TRAIN_FINISH
---@type unitevent
---单位事件: 开始研究科技<br>
---来源: common.j
EVENT_UNIT_RESEARCH_START = common.EVENT_UNIT_RESEARCH_START
---@type unitevent
---单位事件: 取消研究科技<br>
---来源: common.j
EVENT_UNIT_RESEARCH_CANCEL = common.EVENT_UNIT_RESEARCH_CANCEL
---@type unitevent
---单位事件: 完成研究科技<br>
---来源: common.j
EVENT_UNIT_RESEARCH_FINISH = common.EVENT_UNIT_RESEARCH_FINISH
---@type unitevent
---单位事件: 发布命令 (无目标)<br>
---来源: common.j
EVENT_UNIT_ISSUED_ORDER = common.EVENT_UNIT_ISSUED_ORDER
---@type unitevent
---单位事件: 发布命令 (指定点)<br>
---来源: common.j
EVENT_UNIT_ISSUED_POINT_ORDER = common.EVENT_UNIT_ISSUED_POINT_ORDER
---@type unitevent
---单位事件: 发布命令 (指定单位)<br>
---来源: common.j
EVENT_UNIT_ISSUED_TARGET_ORDER = common.EVENT_UNIT_ISSUED_TARGET_ORDER
---@type unitevent
---单位事件: 英雄升级<br>
---来源: common.j
EVENT_UNIT_HERO_LEVEL = common.EVENT_UNIT_HERO_LEVEL
---@type unitevent
---单位事件: 英雄学习技能<br>
---来源: common.j
EVENT_UNIT_HERO_SKILL = common.EVENT_UNIT_HERO_SKILL
---@type unitevent
---单位事件: 英雄可复活/阵亡<br>
---来源: common.j
EVENT_UNIT_HERO_REVIVABLE = common.EVENT_UNIT_HERO_REVIVABLE
---@type unitevent
---单位事件: 英雄开始复活<br>
---来源: common.j
EVENT_UNIT_HERO_REVIVE_START = common.EVENT_UNIT_HERO_REVIVE_START
---@type unitevent
---单位事件: 英雄取消复活<br>
---来源: common.j
EVENT_UNIT_HERO_REVIVE_CANCEL = common.EVENT_UNIT_HERO_REVIVE_CANCEL
---@type unitevent
---单位事件: 英雄完成复活<br>
---来源: common.j
EVENT_UNIT_HERO_REVIVE_FINISH = common.EVENT_UNIT_HERO_REVIVE_FINISH
---@type unitevent
---单位事件: 召唤单位<br>
---来源: common.j
EVENT_UNIT_SUMMON = common.EVENT_UNIT_SUMMON
---@type unitevent
---单位事件: 掉落物品<br>
---来源: common.j
EVENT_UNIT_DROP_ITEM = common.EVENT_UNIT_DROP_ITEM
---@type unitevent
---单位事件: 拾取物品<br>
---来源: common.j
EVENT_UNIT_PICKUP_ITEM = common.EVENT_UNIT_PICKUP_ITEM
---@type unitevent
---单位事件: 使用物品<br>
---来源: common.j
EVENT_UNIT_USE_ITEM = common.EVENT_UNIT_USE_ITEM
---@type unitevent
---单位事件: 单位被装载<br>
---被飞艇、船、被缠绕的金矿等装载<br>
---来源: common.j
EVENT_UNIT_LOADED = common.EVENT_UNIT_LOADED
---@type unitevent
---单位事件: 出售单位<br>
---来源: common.j
EVENT_UNIT_SELL = common.EVENT_UNIT_SELL
---@type unitevent
---单位事件: 单位所属变更<br>
---来源: common.j
EVENT_UNIT_CHANGE_OWNER = common.EVENT_UNIT_CHANGE_OWNER
---@type unitevent
---单位事件: 出售物品<br>
---来源: common.j
EVENT_UNIT_SELL_ITEM = common.EVENT_UNIT_SELL_ITEM
---@type unitevent
---单位事件: 准备施放技能 (前摇开始)<br>
---来源: common.j
EVENT_UNIT_SPELL_CHANNEL = common.EVENT_UNIT_SPELL_CHANNEL
---@type unitevent
---单位事件: 开始施放技能 (前摇结束)<br>
---来源: common.j
EVENT_UNIT_SPELL_CAST = common.EVENT_UNIT_SPELL_CAST
---@type unitevent
---单位事件: 发动技能效果 (后摇开始)<br>
---来源: common.j
EVENT_UNIT_SPELL_EFFECT = common.EVENT_UNIT_SPELL_EFFECT
---@type unitevent
---单位事件: 发动技能结束 (后摇结束)<br>
---来源: common.j
EVENT_UNIT_SPELL_FINISH = common.EVENT_UNIT_SPELL_FINISH
---@type unitevent
---单位事件: 停止施放技能<br>
---来源: common.j
EVENT_UNIT_SPELL_ENDCAST = common.EVENT_UNIT_SPELL_ENDCAST
---@type unitevent
---单位事件: 抵押(卖)物品<br>
---来源: common.j
EVENT_UNIT_PAWN_ITEM = common.EVENT_UNIT_PAWN_ITEM
---@type unitevent
---单位事件: 堆叠物品<br>
---来源: common.j
EVENT_UNIT_STACK_ITEM = common.EVENT_UNIT_STACK_ITEM



---@alias unitstate integer

---@type unitstate
---单位状态: 单位当前生命值<br>
---来源: common.j
UNIT_STATE_LIFE = common.UNIT_STATE_LIFE
---@type unitstate
---单位状态: 单位最大生命值<br>
---来源: common.j
UNIT_STATE_MAX_LIFE = common.UNIT_STATE_MAX_LIFE
---@type unitstate
---单位状态: 单位当前法力值<br>
---来源: common.j
UNIT_STATE_MANA = common.UNIT_STATE_MANA
---@type unitstate
---单位状态: 单位最大法力值<br>
---来源: common.j
UNIT_STATE_MAX_MANA = common.UNIT_STATE_MAX_MANA



---@alias unittype integer

---@type unittype
---单位类型: 英雄<br>
---来源: common.j
UNIT_TYPE_HERO = common.UNIT_TYPE_HERO
---@type unittype
---单位类型: 已死亡<br>
---来源: common.j
UNIT_TYPE_DEAD = common.UNIT_TYPE_DEAD
---@type unittype
---单位类型: 建筑<br>
---来源: common.j
UNIT_TYPE_STRUCTURE = common.UNIT_TYPE_STRUCTURE
---@type unittype
---单位类型: 飞行单位<br>
---来源: common.j
UNIT_TYPE_FLYING = common.UNIT_TYPE_FLYING
---@type unittype
---单位类型: 地面单位<br>
---来源: common.j
UNIT_TYPE_GROUND = common.UNIT_TYPE_GROUND
---@type unittype
---单位类型: 可以攻击飞行单位<br>
---来源: common.j
UNIT_TYPE_ATTACKS_FLYING = common.UNIT_TYPE_ATTACKS_FLYING
---@type unittype
---单位类型: 可以攻击地面单位<br>
---来源: common.j
UNIT_TYPE_ATTACKS_GROUND = common.UNIT_TYPE_ATTACKS_GROUND
---@type unittype
---单位类型: 近战攻击单位<br>
---来源: common.j
UNIT_TYPE_MELEE_ATTACKER = common.UNIT_TYPE_MELEE_ATTACKER
---@type unittype
---单位类型: 远程攻击单位<br>
---来源: common.j
UNIT_TYPE_RANGED_ATTACKER = common.UNIT_TYPE_RANGED_ATTACKER
---@type unittype
---单位类型: 泰坦<br>
---来源: common.j
UNIT_TYPE_GIANT = common.UNIT_TYPE_GIANT
---@type unittype
---单位类型: 召唤物<br>
---来源: common.j
UNIT_TYPE_SUMMONED = common.UNIT_TYPE_SUMMONED
---@type unittype
---单位类型: 被击晕的<br>
---来源: common.j
UNIT_TYPE_STUNNED = common.UNIT_TYPE_STUNNED
---@type unittype
---单位类型: 受折磨的<br>
---来源: common.j
UNIT_TYPE_PLAGUED = common.UNIT_TYPE_PLAGUED
---@type unittype
---单位类型: 被诱捕(被网住)<br>
---来源: common.j
UNIT_TYPE_SNARED = common.UNIT_TYPE_SNARED
---@type unittype
---单位类型: 不死族<br>
---来源: common.j
UNIT_TYPE_UNDEAD = common.UNIT_TYPE_UNDEAD
---@type unittype
---单位类型: 机械<br>
---来源: common.j
UNIT_TYPE_MECHANICAL = common.UNIT_TYPE_MECHANICAL
---@type unittype
---单位类型: 工人<br>
---来源: common.j
UNIT_TYPE_PEON = common.UNIT_TYPE_PEON
---@type unittype
---单位类型: 自爆工兵<br>
---来源: common.j
UNIT_TYPE_SAPPER = common.UNIT_TYPE_SAPPER
---@type unittype
---单位类型: 城镇<br>
---来源: common.j
UNIT_TYPE_TOWNHALL = common.UNIT_TYPE_TOWNHALL
---@type unittype
---单位类型: 古树<br>
---来源: common.j
UNIT_TYPE_ANCIENT = common.UNIT_TYPE_ANCIENT
---@type unittype
---单位类型: 牛头人<br>
---来源: common.j
UNIT_TYPE_TAUREN = common.UNIT_TYPE_TAUREN
---@type unittype
---单位类型: 已中毒<br>
---来源: common.j
UNIT_TYPE_POISONED = common.UNIT_TYPE_POISONED
---@type unittype
---单位类型: 被变形<br>
---来源: common.j
UNIT_TYPE_POLYMORPHED = common.UNIT_TYPE_POLYMORPHED
---@type unittype
---单位类型: 被催眠<br>
---夜晚睡觉也属于被催眠<br>
---来源: common.j
UNIT_TYPE_SLEEPING = common.UNIT_TYPE_SLEEPING
---@type unittype
---单位类型: 有抗性皮肤<br>
---来源: common.j
UNIT_TYPE_RESISTANT = common.UNIT_TYPE_RESISTANT
---@type unittype
---单位类型: 处于虚无状态<br>
---来源: common.j
UNIT_TYPE_ETHEREAL = common.UNIT_TYPE_ETHEREAL
---@type unittype
---单位类型: 免疫魔法<br>
---来源: common.j
UNIT_TYPE_MAGIC_IMMUNE = common.UNIT_TYPE_MAGIC_IMMUNE



---@alias version integer

---@type version
---游戏版本: 混乱之治<br>
---来源: common.j
VERSION_REIGN_OF_CHAOS = common.VERSION_REIGN_OF_CHAOS
---@type version
---游戏版本: 冰封王座<br>
---来源: common.j
VERSION_FROZEN_THRONE = common.VERSION_FROZEN_THRONE



---@alias volumegroup integer

---@type volumegroup
---声音频道: 单位移动声音<br>
---来源: common.j
SOUND_VOLUMEGROUP_UNITMOVEMENT = common.SOUND_VOLUMEGROUP_UNITMOVEMENT
---@type volumegroup
---声音频道: 单位回应声音<br>
---来源: common.j
SOUND_VOLUMEGROUP_UNITSOUNDS = common.SOUND_VOLUMEGROUP_UNITSOUNDS
---@type volumegroup
---声音频道: 战斗声音<br>
---来源: common.j
SOUND_VOLUMEGROUP_COMBAT = common.SOUND_VOLUMEGROUP_COMBAT
---@type volumegroup
---声音频道: 动画和法术声音<br>
---来源: common.j
SOUND_VOLUMEGROUP_SPELLS = common.SOUND_VOLUMEGROUP_SPELLS
---@type volumegroup
---声音频道: 用户界面(UI)声音<br>
---来源: common.j
SOUND_VOLUMEGROUP_UI = common.SOUND_VOLUMEGROUP_UI
---@type volumegroup
---声音频道: 音乐<br>
---来源: common.j
SOUND_VOLUMEGROUP_MUSIC = common.SOUND_VOLUMEGROUP_MUSIC
---@type volumegroup
---声音频道: 场景配音<br>
---来源: common.j
SOUND_VOLUMEGROUP_AMBIENTSOUNDS = common.SOUND_VOLUMEGROUP_AMBIENTSOUNDS
---@type volumegroup
---声音频道: 火焰声音<br>
---来源: common.j
SOUND_VOLUMEGROUP_FIRE = common.SOUND_VOLUMEGROUP_FIRE



---@alias weapontype integer

---@type weapontype
---武器声音: 无<br>
---来源: common.j
WEAPON_TYPE_WHOKNOWS = common.WEAPON_TYPE_WHOKNOWS
---@type weapontype
---武器声音: 金属轻砍<br>
---来源: common.j
WEAPON_TYPE_METAL_LIGHT_CHOP = common.WEAPON_TYPE_METAL_LIGHT_CHOP
---@type weapontype
---武器声音: 金属中砍<br>
---来源: common.j
WEAPON_TYPE_METAL_MEDIUM_CHOP = common.WEAPON_TYPE_METAL_MEDIUM_CHOP
---@type weapontype
---武器声音: 金属重砍<br>
---来源: common.j
WEAPON_TYPE_METAL_HEAVY_CHOP = common.WEAPON_TYPE_METAL_HEAVY_CHOP
---@type weapontype
---武器声音: 金属轻切<br>
---来源: common.j
WEAPON_TYPE_METAL_LIGHT_SLICE = common.WEAPON_TYPE_METAL_LIGHT_SLICE
---@type weapontype
---武器声音: 金属中切<br>
---来源: common.j
WEAPON_TYPE_METAL_MEDIUM_SLICE = common.WEAPON_TYPE_METAL_MEDIUM_SLICE
---@type weapontype
---武器声音: 金属重切<br>
---来源: common.j
WEAPON_TYPE_METAL_HEAVY_SLICE = common.WEAPON_TYPE_METAL_HEAVY_SLICE
---@type weapontype
---武器声音: 金属中击<br>
---来源: common.j
WEAPON_TYPE_METAL_MEDIUM_BASH = common.WEAPON_TYPE_METAL_MEDIUM_BASH
---@type weapontype
---武器声音: 金属重击<br>
---来源: common.j
WEAPON_TYPE_METAL_HEAVY_BASH = common.WEAPON_TYPE_METAL_HEAVY_BASH
---@type weapontype
---武器声音: 金属中刺<br>
---来源: common.j
WEAPON_TYPE_METAL_MEDIUM_STAB = common.WEAPON_TYPE_METAL_MEDIUM_STAB
---@type weapontype
---武器声音: 金属重刺<br>
---来源: common.j
WEAPON_TYPE_METAL_HEAVY_STAB = common.WEAPON_TYPE_METAL_HEAVY_STAB
---@type weapontype
---武器声音: 木头轻切<br>
---来源: common.j
WEAPON_TYPE_WOOD_LIGHT_SLICE = common.WEAPON_TYPE_WOOD_LIGHT_SLICE
---@type weapontype
---武器声音: 木头中切<br>
---来源: common.j
WEAPON_TYPE_WOOD_MEDIUM_SLICE = common.WEAPON_TYPE_WOOD_MEDIUM_SLICE
---@type weapontype
---武器声音: 木头重切<br>
---来源: common.j
WEAPON_TYPE_WOOD_HEAVY_SLICE = common.WEAPON_TYPE_WOOD_HEAVY_SLICE
---@type weapontype
---武器声音: 木头轻击<br>
---来源: common.j
WEAPON_TYPE_WOOD_LIGHT_BASH = common.WEAPON_TYPE_WOOD_LIGHT_BASH
---@type weapontype
---武器声音: 木头中击<br>
---来源: common.j
WEAPON_TYPE_WOOD_MEDIUM_BASH = common.WEAPON_TYPE_WOOD_MEDIUM_BASH
---@type weapontype
---武器声音: 木头重击<br>
---来源: common.j
WEAPON_TYPE_WOOD_HEAVY_BASH = common.WEAPON_TYPE_WOOD_HEAVY_BASH
---@type weapontype
---武器声音: 木头轻刺<br>
---来源: common.j
WEAPON_TYPE_WOOD_LIGHT_STAB = common.WEAPON_TYPE_WOOD_LIGHT_STAB
---@type weapontype
---武器声音: 木头中刺<br>
---来源: common.j
WEAPON_TYPE_WOOD_MEDIUM_STAB = common.WEAPON_TYPE_WOOD_MEDIUM_STAB
---@type weapontype
---武器声音: 利爪轻切<br>
---来源: common.j
WEAPON_TYPE_CLAW_LIGHT_SLICE = common.WEAPON_TYPE_CLAW_LIGHT_SLICE
---@type weapontype
---武器声音: 利爪中切<br>
---来源: common.j
WEAPON_TYPE_CLAW_MEDIUM_SLICE = common.WEAPON_TYPE_CLAW_MEDIUM_SLICE
---@type weapontype
---武器声音: 利爪重切<br>
---来源: common.j
WEAPON_TYPE_CLAW_HEAVY_SLICE = common.WEAPON_TYPE_CLAW_HEAVY_SLICE
---@type weapontype
---武器声音: 斧头中砍<br>
---来源: common.j
WEAPON_TYPE_AXE_MEDIUM_CHOP = common.WEAPON_TYPE_AXE_MEDIUM_CHOP
---@type weapontype
---武器声音: 岩石重击<br>
---来源: common.j
WEAPON_TYPE_ROCK_HEAVY_BASH = common.WEAPON_TYPE_ROCK_HEAVY_BASH



---@alias widgetevent integer

---@type widgetevent
---Widget事件: 单位/物品/可破坏物死亡<br>
---来源: common.j
EVENT_WIDGET_DEATH = common.EVENT_WIDGET_DEATH
