
#define XG_Macro_Set_Act(m,c) XG_Macro_Set(m,[[c]])
#define XG_Macro_Set_Bool(m,c) XG_Macro_Set(m,[[c]])
#define XG_Macro_Set_Boolexpr(m,c) XG_Macro_Set(m,[[c]])
#define XG_Macro_Set_Boolcall(m,c) XG_Macro_Set(m,[[c]])
#define XG_Macro_Set_Str(m,c) XG_Macro_Set(m,[[c]])
#define XG_Macro_Set_Int(m,c) XG_Macro_Set(m,[[c]])
#define XG_Macro_Set_Real(m,c) XG_Macro_Set(m,[[c]])
#define XG_Macro_Set_Unit(m,c) XG_Macro_Set(m,[[c]])
#define XG_Macro_Set_UnitCode(m,c) XG_Macro_Set(m,[[c]])
#define XG_Macro_Set_Item(m,c) XG_Macro_Set(m,[[c]])
#define XG_Macro_Set_ItemCode(m,c) XG_Macro_Set(m,[[c]])
#define XG_Macro_Set_AbilCode(m,c) XG_Macro_Set(m,[[c]])
#define XG_Macro_Set_Player(m,c) XG_Macro_Set(m,[[c]])

#define XG_Macro_Get_Act(m) XG_Macro_Get(m)
#define XG_Macro_Get_Bool(m) XG_Macro_Get(m)
#define XG_Macro_Get_Boolexpr(m) XG_Macro_Get(m)
#define XG_Macro_Get_Boolcall(m) XG_Macro_Get(m)
#define XG_Macro_Get_Str(m) XG_Macro_Get(m)
#define XG_Macro_Get_Int(m) XG_Macro_Get(m)
#define XG_Macro_Get_Real(m) XG_Macro_Get(m)
#define XG_Macro_Get_Unit(m) XG_Macro_Get(m)
#define XG_Macro_Get_UnitCode(m) XG_Macro_Get(m)
#define XG_Macro_Get_Item(m) XG_Macro_Get(m)
#define XG_Macro_Get_ItemCode(m) XG_Macro_Get(m)
#define XG_Macro_Get_AbilCode(m) XG_Macro_Get(m)
#define XG_Macro_Get_Player(m) XG_Macro_Get(m)
