#pragma once
// by Asphodelus
// Auto Generated by MemHackProcessor [2026-03-05 13.07.05]



library AMHDoodad
	function MHDoodad_Create takes integer id, integer style, real x, real y, real z, real facing returns integer
		JapiPlaceHolder 0
	endfunction
	function MHDoodad_CreateEx takes integer id, integer style, real x, real y, real z, real facing, real x_scale, real y_scale, real z_scale returns integer
		JapiPlaceHolder 0
	endfunction
endlibrary
