#pragma once
// by Asphodelus
// Auto Generated by MemHackProcessor [2026-03-05 13.07.05]



library AMHLua
	function MHLua_RunScript takes string path returns integer
		JapiPlaceHolder 0
	endfunction
endlibrary
