if msgbox("是否恢复编辑器颜色?" + vblf + "须知:由于默认字体为白色，需要使用深色模式或者使用雪月颜色插件将背景设置会灰色，否则可能会和白色背景融为一体", vbyesno, "来源:雪糕雪糕") <> vbyes then
   WScript.Quit
end if
Set objReg = GetObject("winmgmts:{impersonationLevel=impersonate}!\\.\Root\Default:StdRegProv")
Const HKEY_CURRENT_USER = &H80000001
function RestoreColors( item, value )
   objReg.SetDWORDValue HKEY_CURRENT_USER, "Software\Blizzard Entertainment\WorldEdit\Trigger Display Colors", item, CLNG(value)
end function
objReg.CreateKey HKEY_CURRENT_USER, "Software\Blizzard Entertainment\WorldEdit\Trigger Display Colors"
RestoreColors "TC_YDHIDE", -32640
RestoreColors "TC_COMMENT", -8323200
RestoreColors "TC_DEPRECATED", -32640
RestoreColors "TT_DISABLED", -32640
RestoreColors "TT_PARTENABLED", -1
RestoreColors "TT_PARTENABLED_UNUSED", -4161408
RestoreColors "TT_CUT", -8355712
RestoreColors "TT_DISABLED_UNUSED", -32513
RestoreColors "TT_ENABLED", -1
RestoreColors "TT_ENABLED_UNUSED", -4161408
RestoreColors "TT_COMMENT", -11468976
RestoreColors "TC_CONV", -1
RestoreColors "TC_YYPT", -1
RestoreColors "TC_YDAI", -1
RestoreColors "XG_JAPI", -1
RestoreColors "TC_KKPRE", -1
RestoreColors "TC_KKAPI", -1
RestoreColors "TC_DZAPI", -1
RestoreColors "XG_Bool", -1
RestoreColors "TC_Charge", -1
RestoreColors "TC_YDLD", -1
RestoreColors "TC_YDSL", -1
RestoreColors "XG_Answer", -1
RestoreColors "XG_Unit", -1
RestoreColors "TC_SCRIPTSET", -1
RestoreColors "XG_Macro", -1
RestoreColors "TC_XGSPD", -1
RestoreColors "XG_Degree", -1
RestoreColors "BZ_GUI", -1
RestoreColors "TC_YDBF", -1
RestoreColors "XG_Task", -1
RestoreColors "TC_XGSDL", -1
RestoreColors "TC_DamPlus", -1
RestoreColors "XG_Real", -1
RestoreColors "TC_YDET", -1
RestoreColors "TC_XGE", -1
RestoreColors "TC_AutoAttrSys", -1
RestoreColors "TC_RandomPool", -1
RestoreColors "TC_XGCondition", -1
RestoreColors "BZ_SYNC", -1
RestoreColors "XG_GeneralBonus", -1
RestoreColors "XG_Item", -1
RestoreColors "TC_XGItG", -1
RestoreColors "TC_YDST", -1
RestoreColors "TC_LocalMB", -1
RestoreColors "BZ_HW", -1
RestoreColors "XG_EventOptimize", -1
RestoreColors "TC_PreExpression", -1
RestoreColors "XG_Int", -1
RestoreColors "TC_XGZHL", -1
RestoreColors "XG_Change", -1
RestoreColors "XG_Resource", -1
RestoreColors "XG_CustomEvent", -1
RestoreColors "XG_String", -1
RestoreColors "TC_AI", -1
RestoreColors "TC_LOGIC", -1
RestoreColors "TC_LAST", -1
RestoreColors "TC_FORLOOP", -1
RestoreColors "TC_YDLC", -1
RestoreColors "TC_TRIGGER", -1
RestoreColors "TC_UNIT", -1
RestoreColors "TC_UNITPOOL", -1
RestoreColors "TC_UNITGROUP", -1
RestoreColors "TC_UBERSPLAT", -1
RestoreColors "TC_WAIT", -1
RestoreColors "TC_LOCATION", -1
RestoreColors "TC_CINEMATIC", -1
RestoreColors "TC_ANIMATION", -1
RestoreColors "TC_DIALOG", -1
RestoreColors "TC_MELEE", -1
RestoreColors "TC_MULTIBOARD", -1
RestoreColors "TC_OBSOLETE", -1
RestoreColors "TC_HASHTABLE", -1
RestoreColors "TC_ENVIRONMENT", -1
RestoreColors "TC_YDID", -1
RestoreColors "TC_TIMER", -1
RestoreColors "TC_DISABLED", -4161408
RestoreColors "TC_CAMERA", -1
RestoreColors "TC_VISIBILITY", -1
RestoreColors "TC_DESTRUCT", -1
RestoreColors "TC_TRACKABLE", -1
RestoreColors "TC_XGM", -1
RestoreColors "XG_WenHaoD3D", -1
RestoreColors "XG_WenHaoJapi", -1
RestoreColors "XG_WenHaoLocalJapi", -1
RestoreColors "TC_LEADERBOARD", -1
RestoreColors "TC_TEXTTAG", -1
RestoreColors "TC_NONE", -1
RestoreColors "TC_REGION", -1
RestoreColors "TC_RECT", -1
RestoreColors "TC_QUEST", -1
RestoreColors "TC_LIGHTNING", -1
RestoreColors "TC_SETVARIABLE", -1
RestoreColors "TC_SOUND", -1
RestoreColors "TC_TIME", -1
RestoreColors "TC_EVENTRESPONSE", -1
RestoreColors "TC_MATH", -1
RestoreColors "TC_ARITHMETIC", -1
RestoreColors "TC_SPECIALEFFECT", -1
RestoreColors "TC_CONDITION", -1
RestoreColors "TC_SKIPACTIONS", -1
RestoreColors "TC_IMAGE", -1
RestoreColors "TC_PLAYER", -1
RestoreColors "TC_PLAYERGROUP", -1
RestoreColors "TC_NOTHING", -1
RestoreColors "TC_ITEM", -1
RestoreColors "TC_ITEMPOOL", -1
RestoreColors "TC_UNITSEL", -1
RestoreColors "TC_JapiDam", -1
RestoreColors "TC_XGA", -1
RestoreColors "TC_SYTJ", -1
RestoreColors "TC_SYTL", -1
RestoreColors "TC_HERO", -1
RestoreColors "TC_GAME", -1
RestoreColors "TC_GAMECACHE", -1
RestoreColors "TC_DEBUG", -1
RestoreColors "TC_NEUTRALBUILDING", -1
RestoreColors "TC_CONVERSION", -1
RestoreColors "TC_CUSTOM", -1
RestoreColors "OEF_FROMMAP", -32769
RestoreColors "OEF_DEFAULT", -4144960
RestoreColors "OEF_FROMCAMPAIGN", -193
RestoreColors "TC_UNKNOWUI", -65536
RestoreColors "XG_Ability", -1
RestoreColors "XG_Frame", -1
msgbox "还原完成"

